package com.beloucif.latournee.core

/**
 * La Criée - embedded game mode, no content pack (mirrors la-taverne/src/content/auction.ts).
 * Surenchère themes only, 100% original, store-safe by construction: never a named alcohol.
 */
data class AuctionTheme(
    val id: String,
    val text: String,
)

val AUCTION_THEMES: List<AuctionTheme> = listOf(
    AuctionTheme("au-01", "Des capitales européennes"),
    AuctionTheme("au-02", "Des films avec des super-héros"),
    AuctionTheme("au-03", "Des marques de voitures"),
    AuctionTheme("au-04", "Des joueurs de foot français"),
    AuctionTheme("au-05", "Des animaux qui vivent dans la savane"),
    AuctionTheme("au-06", "Des chansons de Disney"),
    AuctionTheme("au-07", "Des sortes de fromages"),
    AuctionTheme("au-08", "Des séries Netflix"),
    AuctionTheme("au-09", "Des pays d'Afrique"),
    AuctionTheme("au-10", "Des prénoms commençant par la lettre M"),
    AuctionTheme("au-11", "Des métiers qui font peur"),
    AuctionTheme("au-12", "Des choses qu'on trouve dans une trousse"),
    AuctionTheme("au-13", "Des sports olympiques"),
    AuctionTheme("au-14", "Des pizzas différentes"),
    AuctionTheme("au-15", "Des rappeurs ou rappeuses francophones"),
    AuctionTheme("au-16", "Des personnages de dessins animés"),
    AuctionTheme("au-17", "Des villes françaises de plus de 100 000 habitants"),
    AuctionTheme("au-18", "Des marques de vêtements"),
    AuctionTheme("au-19", "Des choses qu'on emporte à la plage"),
    AuctionTheme("au-20", "Des instruments de musique"),
    AuctionTheme("au-21", "Des excuses classiques pour un retard"),
    AuctionTheme("au-22", "Des films d'horreur"),
    AuctionTheme("au-23", "Des mots qui riment avec « soirée »"),
    AuctionTheme("au-24", "Des émissions de télé-réalité"),
    AuctionTheme("au-25", "Des sortes de pâtes"),
    AuctionTheme("au-26", "Des pays où il fait (très) chaud"),
    AuctionTheme("au-27", "Des choses jaunes"),
    AuctionTheme("au-28", "Des applis présentes sur presque tous les téléphones"),
    AuctionTheme("au-29", "Des super-pouvoirs"),
    AuctionTheme("au-30", "Des choses qu'on fait semblant d'aimer en famille"),
    AuctionTheme("au-31", "Des animaux marins"),
    AuctionTheme("au-32", "Des jeux de société"),
    AuctionTheme("au-33", "Des acteurs ou actrices français"),
    AuctionTheme("au-34", "Des choses dans un sac à main"),
    AuctionTheme("au-35", "Des langues parlées dans le monde"),
    AuctionTheme("au-36", "Des desserts français"),
    AuctionTheme("au-37", "Des groupes ou chanteurs des années 80"),
    AuctionTheme("au-38", "Des raisons de quitter une soirée"),
    AuctionTheme("au-39", "Des choses qui se mangent crues"),
    AuctionTheme("au-40", "Des monuments célèbres dans le monde"),
    AuctionTheme("au-41", "Des mots d'argot pour dire « argent »"),
    AuctionTheme("au-42", "Des sports qui se jouent avec une balle ou un ballon"),
    AuctionTheme("au-43", "Des personnages de Harry Potter"),
    AuctionTheme("au-44", "Des choses qu'on trouve dans une cuisine"),
    AuctionTheme("au-45", "Des marques de céréales ou de biscuits"),
    AuctionTheme("au-46", "Des îles"),
    AuctionTheme("au-47", "Des choses qui piquent"),
    AuctionTheme("au-48", "Des films romantiques"),
    AuctionTheme("au-49", "Des choses qu'on fait avant de dormir"),
    AuctionTheme("au-50", "Des animaux plus petits qu'une main"),
)
