package com.beloucif.bacchana.core

/**
 * Tu preferes - embedded mode, no content pack (mirrors la-taverne's dilemma
 * bank). 84 dilemmas A or B, store-safe by construction: never a named alcohol.
 */
data class WouldYouRatherQuestion(
    val id: String,
    val optionA: String,
    val optionB: String,
)

val WOULD_YOU_RATHER_QUESTIONS: List<WouldYouRatherQuestion> = listOf(
    WouldYouRatherQuestion("wyr-001", "Avoir le hoquet toute ta vie", "Éternuer 20 fois par jour"),
    WouldYouRatherQuestion("wyr-002", "Pouvoir voler mais seulement 30cm du sol", "Marcher sur l'eau seulement la nuit"),
    WouldYouRatherQuestion("wyr-003", "Parler comme une célébrité étrangère toute ta vie", "Avoir un accent bizarre incurable"),
    WouldYouRatherQuestion("wyr-004", "Cheveux qui changent de couleur selon ton humeur", "Peau qui rougit chaque fois que tu mens"),
    WouldYouRatherQuestion("wyr-005", "Vivre dans une maison faite uniquement de portes vitrées", "Vivre dans une maison faite uniquement d'escaliers en colimaçon"),
    WouldYouRatherQuestion("wyr-006", "Porter des chaussures trop petites toute ta vie", "Porter des chaussures trop grandes toute ta vie"),
    WouldYouRatherQuestion("wyr-007", "Avoir des mains de T-Rex", "Avoir des jambes très courtes style mascotte"),
    WouldYouRatherQuestion("wyr-008", "Manger uniquement des pâtes à vie", "Manger uniquement du pain complet à vie"),
    WouldYouRatherQuestion("wyr-009", "Avoir un klaxon à la place de la voix", "Crier comme un bébé toujours"),
    WouldYouRatherQuestion("wyr-010", "Oublier le nom de quelqu'un immédiatement après", "Confondre toujours les visages"),
    WouldYouRatherQuestion("wyr-011", "Vivre en noir et blanc", "Vivre en rose fluo permanent"),
    WouldYouRatherQuestion("wyr-012", "Avoir une queue visible permanente", "Avoir des oreilles pointues de lutin"),
    WouldYouRatherQuestion("wyr-013", "Rire sans t'arrêter dans les moments graves", "Ne plus jamais pouvoir rire"),
    WouldYouRatherQuestion("wyr-014", "Marcher à reculons toujours", "Marcher de travers comme un crabe"),
    WouldYouRatherQuestion("wyr-015", "Avoir une sonnette à la place de la voix", "Avoir un bruiteur d'ascenseur comme voix"),
    WouldYouRatherQuestion("wyr-016", "Dormir debout comme un cheval", "Dormir appuyé contre un mur"),
    WouldYouRatherQuestion("wyr-017", "Avoir des cornes ornementales", "Avoir une corne de licorne sur le front"),
    WouldYouRatherQuestion("wyr-018", "Voir en rayons X toujours", "Voir en caméra thermique"),
    WouldYouRatherQuestion("wyr-019", "Ta voix descend d'une octave par an", "Ta voix monte d'une octave par an"),
    WouldYouRatherQuestion("wyr-020", "Avoir des griffes de chat", "Avoir des crocs de vampire"),
    WouldYouRatherQuestion("wyr-021", "Danser involontairement chaque jeudi", "Danser involontairement dès que quelqu'un crie"),
    WouldYouRatherQuestion("wyr-022", "Changer de taille au hasard entre 10cm et 3m", "Peser au hasard entre 10kg et 200kg"),
    WouldYouRatherQuestion("wyr-023", "Aimanter les objets métalliques", "Générer des étincelles en frottant tes mains"),
    WouldYouRatherQuestion("wyr-024", "Avoir des ailes de papillon", "Avoir des ailes de chauve-souris"),
    WouldYouRatherQuestion("wyr-025", "Avoir une bande sonore épique qui te suit", "Avoir des effets sonores de jeu vidéo aléatoires"),
    WouldYouRatherQuestion("wyr-026", "Parler par télépathie mais très fort", "Crier toujours en chuchotant"),
    WouldYouRatherQuestion("wyr-027", "Avoir les yeux qui brillent la nuit", "Avoir les yeux qui changent avec tes émotions"),
    WouldYouRatherQuestion("wyr-028", "Avoir une moustache permanente", "Avoir une barbe pixelisée"),
    WouldYouRatherQuestion("wyr-029", "Sentir la fraise toute ta vie", "Sentir l'essence toute ta vie"),
    WouldYouRatherQuestion("wyr-030", "Avoir des tentacules à la place des bras", "Avoir des tentacules à la place des jambes"),
    WouldYouRatherQuestion("wyr-031", "Rougir violemment face à quelqu'un qui te plaît", "Transpirer dès que tu stresses"),
    WouldYouRatherQuestion("wyr-032", "Vivre dans un monde en Sims pixelisés", "Vivre dans un monde en animé 2D"),
    WouldYouRatherQuestion("wyr-033", "Avoir un seul sourcil permanent", "Ne pas avoir de sourcils du tout"),
    WouldYouRatherQuestion("wyr-034", "Avoir des pieds de canard", "Avoir des mains de singe"),
    WouldYouRatherQuestion("wyr-035", "Avoir la voix qui se brise quand tu cries", "Crier comme une fillette toujours"),
    WouldYouRatherQuestion("wyr-036", "Que ton crush te voie au pire moment possible", "Texter par erreur un truc cringe à ton crush"),
    WouldYouRatherQuestion("wyr-037", "Avoir une tache noire entre les dents une journée", "Marcher toute la journée avec du PQ sous la chaussure"),
    WouldYouRatherQuestion("wyr-038", "Croiser ton ex au pire moment", "Que ton crush arrive juste à ce moment-là"),
    WouldYouRatherQuestion("wyr-039", "Avoir le hoquet en pleine présentation", "Bafouiller devant toute la classe"),
    WouldYouRatherQuestion("wyr-040", "Appeler ta prof maman une fois", "Crier le nom de ton crush devant tout le monde"),
    WouldYouRatherQuestion("wyr-041", "Avoir une verrue visible sur le visage", "Avoir une cicatrice bizarre bien visible"),
    WouldYouRatherQuestion("wyr-042", "Envoyer un message cringe à ton crush", "Lui envoyer une photo pas terrible de toi"),
    WouldYouRatherQuestion("wyr-043", "Avoir une voix très grave pendant un mois", "Avoir la voix d'un enfant de 5 ans pendant un mois"),
    WouldYouRatherQuestion("wyr-044", "Que ton groupe apprenne un secret gênant sur toi", "Apprendre un secret gênant sur ton meilleur ami"),
    WouldYouRatherQuestion("wyr-045", "Avoir le visage plein de boutons une semaine", "Avoir une coupe de cheveux ratée un mois"),
    WouldYouRatherQuestion("wyr-046", "Oublier le prénom de ton rendez-vous", "L'appeler par le prénom de ton ex"),
    WouldYouRatherQuestion("wyr-047", "Avoir des tics nerveux visibles quand tu stresses", "Bafouiller complètement en parlant"),
    WouldYouRatherQuestion("wyr-048", "Te sentir observé par quelqu'un qui te plaît", "Te sentir observé par quelqu'un pas ton type"),
    WouldYouRatherQuestion("wyr-049", "Voir ton crush avec quelqu'un d'autre", "Que ton crush te voie avec quelqu'un d'autre"),
    WouldYouRatherQuestion("wyr-050", "Trébucher devant la personne qui te plaît", "Renverser ton verre sur elle"),
    WouldYouRatherQuestion("wyr-051", "Transpirer beaucoup à un premier rendez-vous", "Bafouiller et rougir sans t'arrêter"),
    WouldYouRatherQuestion("wyr-052", "Avoir un vieux post cringe qui refait surface", "Avoir une photo de classe humiliante qui circule"),
    WouldYouRatherQuestion("wyr-053", "Que ton crush voie une vidéo embarrassante de toi", "Que ton crush lise tes vieux messages cringes"),
    WouldYouRatherQuestion("wyr-054", "Rire nerveusement dans un moment sérieux", "Pleurer devant tout le monde pour rien"),
    WouldYouRatherQuestion("wyr-055", "Avoir constamment les joues rouges", "Avoir une expression gênante figée sur le visage"),
    WouldYouRatherQuestion("wyr-056", "Appeler quelqu'un par le nom de son ex", "Oublier complètement le prénom d'un proche"),
    WouldYouRatherQuestion("wyr-057", "Craquer pour ton boss", "Craquer pour ton meilleur ami déjà en couple"),
    WouldYouRatherQuestion("wyr-058", "Avoir un crush sur un cousin lointain", "Avoir un crush sur la meilleure amie de ton ex"),
    WouldYouRatherQuestion("wyr-059", "Avoir un crush beaucoup plus jeune", "Avoir un crush beaucoup plus vieux"),
    WouldYouRatherQuestion("wyr-060", "Flasher sur le rendez-vous de ton meilleur ami", "Flasher sur l'ex de ta sœur"),
    WouldYouRatherQuestion("wyr-061", "Envoyer un message gênant à tout ton groupe", "Envoyer ce même message à ta mère"),
    WouldYouRatherQuestion("wyr-062", "Avoir une trace de sueur permanente sur ta chemise", "Avoir une tache bien visible sur ton pantalon"),
    WouldYouRatherQuestion("wyr-063", "Dire je t'aime par erreur à la caissière", "Dire je t'aime par erreur au livreur"),
    WouldYouRatherQuestion("wyr-064", "Avoir un accent bizarre quand tu es nerveux", "Bégayer dès que tu parles à quelqu'un"),
    WouldYouRatherQuestion("wyr-065", "Ne plus jamais ressentir le frisson d'un crush", "Tomber amoureux toutes les semaines"),
    WouldYouRatherQuestion("wyr-066", "Te trouver irrésistible en permanence", "Penser que personne ne te remarque jamais"),
    WouldYouRatherQuestion("wyr-067", "Que ton crush t'envoie un message flirty par erreur", "Que ton crush like toutes tes vieilles photos"),
    WouldYouRatherQuestion("wyr-068", "Avouer ton crush et te prendre un râteau", "Ne jamais oser et le regretter à vie"),
    WouldYouRatherQuestion("wyr-069", "Embrasser quelqu'un et que ce soit très gênant", "Rater le moment parfait pour un premier baiser"),
    WouldYouRatherQuestion("wyr-070", "Que ton ex débarque avec sa nouvelle copine", "Que ton ex débarque au bras de ta meilleure amie"),
    WouldYouRatherQuestion("wyr-071", "Tenter ta chance au risque de perdre l'amitié", "Garder l'amitié et enterrer tes sentiments"),
    WouldYouRatherQuestion("wyr-072", "Avoir un crush sur quelqu'un d'inaccessible", "Avoir un crush sur quelqu'un que tes amis détestent"),
    WouldYouRatherQuestion("wyr-073", "Être attiré par deux personnes à la fois", "Que deux personnes soient attirées par toi en même temps"),
    WouldYouRatherQuestion("wyr-074", "Un premier rendez-vous parfait mais sans aucun courant", "Un premier rendez-vous catastrophique mais plein de papillons"),
    WouldYouRatherQuestion("wyr-075", "Que ton crush connaisse tous tes secrets", "Connaître tous les secrets de ton crush"),
    WouldYouRatherQuestion("wyr-076", "Devoir choisir entre ta carrière et l'amour", "Devoir choisir entre ta liberté et une relation sérieuse"),
    WouldYouRatherQuestion("wyr-077", "Que ton crush voie ta liste de crushs passés", "Voir la liste des crushs passés de ton crush"),
    WouldYouRatherQuestion("wyr-078", "Être obsédé par une célébrité inatteignable", "Être obsédé par quelqu'un que tu devrais éviter"),
    WouldYouRatherQuestion("wyr-079", "Vouloir avancer alors que l'autre freine", "Que l'autre veuille avancer alors que tu freines"),
    WouldYouRatherQuestion("wyr-080", "Que ton journal intime soit lu par ton groupe", "Que ton journal intime soit lu par tes parents"),
    WouldYouRatherQuestion("wyr-081", "Déclarer ta flamme en public et te faire jeter", "Apprendre que ton crush t'aimait mais a abandonné"),
    WouldYouRatherQuestion("wyr-082", "Avoir du mal à dire ce que tu ressens", "Tout dire trop vite et faire fuir les gens"),
    WouldYouRatherQuestion("wyr-083", "Te faire surprendre en train de mater ton crush", "Surprendre ton crush en train de te mater"),
    WouldYouRatherQuestion("wyr-084", "Choisir quelqu'un d'ultra attirant mais distant", "Choisir quelqu'un de banal mais fou de toi"),
)
