package com.beloucif.meskova.content

import android.content.Context
import com.beloucif.meskova.core.ContentPack
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.json.Json

/**
 * Loads bundled free packs (assets/packs, *.json files) and the premium catalog metadata
 * (assets/premium-catalog.json) generated by scripts/sync_content.py from
 * la-taverne-content. Premium pack bodies are never bundled - only their metadata,
 * so the app stays a legitimate free download with a real in-app purchase upsell.
 */
class PackRepository(private val context: Context) {

    private val json = Json { ignoreUnknownKeys = true }

    private val packCache = mutableMapOf<String, ContentPack>()
    private var premiumCatalogCache: List<PremiumCatalogEntry>? = null

    /** Lists the file names (without extension) of every bundled free pack. */
    suspend fun listFreePackIds(): List<String> = withContext(Dispatchers.IO) {
        context.assets.list(PACKS_DIR)
            ?.filter { it.endsWith(".json") }
            ?.map { it.removeSuffix(".json") }
            ?.sorted()
            ?: emptyList()
    }

    /** Loads and caches one bundled free pack by id (file name without extension). */
    suspend fun loadPack(packId: String): Result<ContentPack> = withContext(Dispatchers.IO) {
        runCatching {
            packCache.getOrPut(packId) {
                val raw = context.assets.open("$PACKS_DIR/$packId.json").bufferedReader(Charsets.UTF_8).use { it.readText() }
                json.decodeFromString(ContentPackDto.serializer(), raw).toCore()
            }
        }
    }

    /** Loads every bundled free pack for a given mode (matched after decoding). */
    suspend fun loadFreePacksForMode(mode: com.beloucif.meskova.core.GameMode): List<ContentPack> {
        val ids = listFreePackIds()
        return ids.mapNotNull { id -> loadPack(id).getOrNull() }.filter { it.pack.mode == mode }
    }

    /** Loads the premium catalog (metadata only, no prompt text) for locked-tile display. */
    suspend fun loadPremiumCatalog(): List<PremiumCatalogEntry> = withContext(Dispatchers.IO) {
        premiumCatalogCache ?: runCatching {
            val raw = context.assets.open(PREMIUM_CATALOG_FILE).bufferedReader(Charsets.UTF_8).use { it.readText() }
            json.decodeFromString(kotlinx.serialization.builtins.ListSerializer(PremiumCatalogEntryDto.serializer()), raw)
                .map { it.toCore() }
        }.getOrDefault(emptyList()).also { premiumCatalogCache = it }
    }

    private companion object {
        const val PACKS_DIR = "packs"
        const val PREMIUM_CATALOG_FILE = "premium-catalog.json"
    }
}
