package com.beloucif.bacchus.content

import com.beloucif.bacchus.core.GameMode
import com.beloucif.bacchus.core.Intensity
import kotlinx.serialization.Serializable

/**
 * Metadata-only entry for a premium pack: shown as a locked tile before purchase.
 * Generated by scripts/sync_content.py from bacchus-content, contains no prompt text.
 */
@Serializable
data class PremiumCatalogEntryDto(
    val id: String,
    val mode: GameModeDto,
    val title: String,
    val subtitle: String,
    val intensity: IntensityDto,
    val itemCount: Int,
)

data class PremiumCatalogEntry(
    val id: String,
    val mode: GameMode,
    val title: String,
    val subtitle: String,
    val intensity: Intensity,
    val itemCount: Int,
)

fun PremiumCatalogEntryDto.toCore(): PremiumCatalogEntry = PremiumCatalogEntry(
    id = id,
    mode = mode.toCore(),
    title = title,
    subtitle = subtitle,
    intensity = intensity.toCore(),
    itemCount = itemCount,
)
